In [ ]:
"""
Sim:
- Text
- comments
"""
"""
Sort:
- City BOOLEN DONE

- price SORT 
- People SORT
- beds SORT
- number_of_reviews SORT
- 
"""
"""
Leave:
- 'index', 'id', 'listing_url','neighbourhood_cleansed','latitude', 'longitude','instant_bookable','accommodates','beds', maximum_nights, minimum_nights, 'name','description','amenities'
"""
"""

"""

In [1]:
import sys

# Add a path to sys.path
sys.path.append('../datasets')


from Airbnb_data import Airbnb_data
df = Airbnb_data()

In [3]:
df.sort_values('number_of_reviews')['number_of_reviews']

13999       4
13938       4
13939       4
13940       4
13941       4
         ...
10002     915
10001     928
10000    1011
4001     1044
4000     1612
Name: number_of_reviews, Length: 14000, dtype: int64

In [3]:
df.groupby('City').count()

,id,listing_url,description,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,price,minimum_nights,maximum_nights,has_availability,number_of_reviews,instant_bookable,comments,Text,People,Min_Duration
City,,,,,,,,,,,,,,,,,,,,,
Barcelona,11550,11550,11550,11550,11550,11550,11550,11550,11550,11550,...,11550,11550,11550,11550,11550,11550,11550,11550,11550,11550
Girona,13969,13969,13969,13969,13969,13969,13969,13969,13969,13969,...,13969,13969,13969,13969,13969,13969,13969,13969,13969,13969
Madrid,15465,15465,15465,15465,15465,15465,15465,15465,15465,15465,...,15465,15465,15465,15465,15465,15465,15465,15465,15465,15465
Malaga,6082,6082,6082,6082,6082,6082,6082,6082,6082,6082,...,6082,6082,6082,6082,6082,6082,6082,6082,6082,6082
Mallorca,12050,12050,12050,12050,12050,12050,12050,12050,12050,12050,...,12050,12050,12050,12050,12050,12050,12050,12050,12050,12050
Menorca,2699,2699,2699,2699,2699,2699,2699,2699,2699,2699,...,2699,2699,2699,2699,2699,2699,2699,2699,2699,2699
Sevilla,5961,5961,5961,5961,5961,5961,5961,5961,5961,5961,...,5961,5961,5961,5961,5961,5961,5961,5961,5961,5961

In [1]:
import sys

# Add a path to sys.path
sys.path.append('../datasets')

In [2]:
from Airbnb_reco import model_computations

In [3]:
titles_air,indices_air, cosine_sim_air, df = model_computations('comments')

50 PERCENT

In [4]:
import numpy as np
titles_air.to_csv('titles_comments_air.csv',index=False)
indices_air.to_csv('indices_comments_air.csv',index=False)
np.save('cosine_sim_comments_air.npy', cosine_sim_air)

NameError: name 'titles_air' is not defined

In [21]:
import sys

# Add a path to sys.path
sys.path.append('../datasets')

import pandas as pd
from Airbnb_data import Airbnb_data
df = Airbnb_data()
#listing_df_madrid = pd.read_csv("../datasets/data_files/listings_mad.csv")
#review_df_madrid = pd.read_csv("../datasets/data_files/reviews_mad.csv")

/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/Airbnb_data.py:216: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  result_df['price'] = result_df['price']/100

In [ ]:
df.to_csv('airbnb_clean.csv',index=False)

In [3]:
from Airbnb_reco import Airbnb_reco

In [35]:
df['People'].min()

0.1

In [8]:
import numpy as np
import sys
import pandas as pd
# Add a path to sys.path
sys.path.append('../datasets')

#titles,indices, cosine_sim, df = model_computations()
titles = pd.read_csv('../datasets/data_files/titles_air.csv')
df = pd.read_csv('../datasets/data_files/airbnb_clean.csv')
df2 = df.reset_index()
titles = pd.Series(df2['Text'])
indices = pd.Series(df2.index, index = df2['Text'])
cosine_sim = np.load('../datasets/data_files/cosine_sim_air.npy')

In [9]:
from Airbnb_reco import Airbnb_reco
#r = Airbnb_reco('Malaga',50059918,200,10,2,100,titles,indices, cosine_sim, df)

In [10]:
def Rent_Reco(location,previous,best_price,best_beds,best_People,best_reviews):
        
    recos = Airbnb_reco(location,previous,best_price,best_beds,best_People,best_reviews,titles,indices, cosine_sim, df)
    return recos.head(50)

In [11]:
import pandas as pd

df = pd.read_csv('../datasets/data_files/airbnb_clean.csv')

import sys
sys.path.append('../datasets')
from userdata import users
import numpy as np
from data_structure import data_strcture
_, user_df, pool_df = data_strcture()

/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/Flights.py:12: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df['bags_price'] = grouped_bag['bags_price'].apply(lambda x: x.fillna(x.dropna().iloc[0]) if x.isnull().values.any() else x)
/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/Flights.py:13: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df['availability'] = grouped_avl['availability'].apply(lambda x: x.fillna(x.dropna().iloc[0]) if x.isnull().values.any() else x)
/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/data_structure.py:86: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pool_df[x] = y

In [12]:
pool_df, updated_user_df = users(1 ,df, user_df, pool_df, 'Madrid', 'Historical', 900,900,5,10,800, '2023-04-15 14:30:45', 1)

/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/userdata.py:117: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pool_df = pool_df.append(new_row, ignore_index=True)

In [24]:
from Ranges import Ranges
from statistics import mean
#pool_df, updated_user_df = users(1 ,df, user_df, pool_df, 'Madrid', 'Historical', 900,900,5,10,800, '2023-04-15 14:30:45', 0)

price_ranges, time_cols_dict, cities_dict, price_ranges_air, beds_ranges, people_ranges, reviews_ranges = Ranges()
City = 'Madrid' #inputed
prev = 50059918 # recursive
price_flight = 200 #inputed
category = 'Historical' #inputed
time = '2023-04-15 14:30:45' #inputed

#-------------------------
price_max_air = user_df[user_df['UserId'] == 1].filter(regex='PriceLvl.*airbnb').idxmax(axis=1)
beds_max_air = user_df[user_df['UserId']==1].filter(like='Beds_').idxmax(axis=1)
people_max_air = user_df[user_df['UserId']==1].filter(like='People_').idxmax(axis=1)
reviews_max_air = user_df[user_df['UserId']==1].filter(like='Reviews_').idxmax(axis=1)

best_price_air = mean(price_ranges_air[str(price_max_air)[5:-14]])
best_beds_air = mean(beds_ranges[str(beds_max_air)[5:-14]])
best_people_air = mean(people_ranges[str(people_max_air)[5:-14]])
best_reviews_air = mean(reviews_ranges[str(reviews_max_air)[5:-14]])
# ---------------------------
print(City,prev, best_price_air,best_beds_air,best_people_air, best_reviews_air)

reco = Rent_Reco(City,prev, best_price_air,best_beds_air,best_people_air, best_reviews_air)
#r = Airbnb_reco('Malaga',50059918,200,10,2,100,titles,indices, cosine_sim, df)


reco = reco.sort_values(['fear', 'anger', 'negative', 'sadness', 'disgust',]).sort_values([ 'number_of_reviews','trust', 'surprise','positive',  'joy'],ascending=False)
reco = reco.head(10)
print(reco['listing_url'].iloc[0])
print("Do you like this offer? 1 for yes, 0 for no")
indicator = input()
pool_df, updated_user_df = users(1 ,df, user_df, pool_df, reco['City'].iloc[0], category, price_flight,reco['price'].iloc[0],reco['beds'].iloc[0],reco['People'].iloc[0],reco['number_of_reviews'].iloc[0], time, int(indicator))

Madrid 50059918 50 1.5 1.5 700
Preciosa y espaciosa habitaciÃ³n con cama de matrimonio. Toallas (no de playa) y sabanas incluidas.<br />Agua mineral en la habitaciÃ³n y calentador de agua.<br />CalefacciÃ³n central. Parquet en toda la casa. Cuarto de baÃ±o completo.<br />SEGUIMOS LAS INDICACIONES DE LIMPIEZA E HIGIENE DE AIRBNB<br />Con persiana para bloquear la luz completamente<br />TV Y NEVERITA son para tu uso exclusivo, armario,  escritorio y wifi (FIBRA Ã“PTICA) <br />Zona a 10 minutos de la Plaza EspaÃ±a, autobÃºs en puerta<br /><br /><b>The space</b><br />Luminosa habitaciÃ³n exterior en zona cÃ©ntrica de Palma, a 10 minutos paseando de la Plaza EspaÃ±a.<br />Todos los servicios (gimnasios, cines, bares, pub's, restaurantes, supermercados, bus ...)PregÃºntame y te ayudare a encontrar los mejores sitios de Palma. <br />Si deseas cuna, hazmelo saber!<br />OpciÃ³n a cama adicional para tercer huÃ©sped.<br /><br /><b>Guest access</b><br />HabitaciÃ³n privada con televisiÃ³n y neverita solo para ti.<br />BaÃ±o completo (compartiHABITACION 2+1 CERCA CENTRO["Mini fridge", "Extra pillows and blankets", "HDTV with standard cable", "Carbon monoxide alarm", "Room-darkening shades", "Ceiling fan", "Ethernet connection", "Clamp on table seat high chair", "Hot water kettle", "Laundromat nearby", "Children\u2019s dinnerware", "Lock on bedroom door", "Dedicated workspace", "Paid parking off premises", "Dishes and silverware", "Hangers", "Single level home", "Babysitter recommendations", "Long term stays allowed", "Shower gel", "First aid kit", "Bed linens", "Free street parking", "Body soap", "Host greets you", "Clothing storage: closet", "Hair dryer", "Shampoo", "Hot water", "Central heating", "Portable fans", "Wifi", "Fire extinguisher", "Mountain view", "Essentials", "Elevator", "Smoke alarm"]
----------
134
----------
https://www.airbnb.com/rooms/12064892
Do you like this offer? 1 for yes, 0 for no

/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/userdata.py:117: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pool_df = pool_df.append(new_row, ignore_index=True)

In [30]:
from Ranges import Ranges
from statistics import mean
#pool_df, updated_user_df = users(1 ,df, user_df, pool_df, 'Madrid', 'Historical', 900,900,5,10,800, '2023-04-15 14:30:45', 0)
def clf_airbnb(UserId,user_df,pool_df,City,price_flight,category,time,prev = 50059918):
    price_ranges, time_cols_dict, cities_dict, price_ranges_air, beds_ranges, people_ranges, reviews_ranges = Ranges()
    #City = 'Madrid' #inputed
    #prev = 50059918 # recursive
    #price_flight = 200 #inputed
    #category = 'Historical' #inputed
    #time = '2023-04-15 14:30:45' #inputed

    #-------------------------
    price_max_air = user_df[user_df['UserId'] == UserId].filter(regex='PriceLvl.*airbnb').idxmax(axis=1)
    beds_max_air = user_df[user_df['UserId']==UserId].filter(like='Beds_').idxmax(axis=1)
    people_max_air = user_df[user_df['UserId']==UserId].filter(like='People_').idxmax(axis=1)
    reviews_max_air = user_df[user_df['UserId']==UserId].filter(like='Reviews_').idxmax(axis=1)

    best_price_air = mean(price_ranges_air[str(price_max_air)[5:-14]])
    best_beds_air = mean(beds_ranges[str(beds_max_air)[5:-14]])
    best_people_air = mean(people_ranges[str(people_max_air)[5:-14]])
    best_reviews_air = mean(reviews_ranges[str(reviews_max_air)[5:-14]])
    # ---------------------------
    print(City,prev, best_price_air,best_beds_air,best_people_air, best_reviews_air)

    reco = Rent_Reco(City,prev, best_price_air,best_beds_air,best_people_air, best_reviews_air)
    #r = Airbnb_reco('Malaga',50059918,200,10,2,100,titles,indices, cosine_sim, df)


    reco = reco.sort_values(['fear', 'anger', 'negative', 'sadness', 'disgust',]).sort_values([ 'number_of_reviews','trust', 'surprise','positive',  'joy'],ascending=False)
    reco = reco.head(10)
    print(reco['listing_url'].iloc[0])
    print("Do you like this offer? 1 for yes, 0 for no")
    indicator = input()
    pool_df, updated_user_df = users(UserId ,df, user_df, pool_df, reco['City'].iloc[0], category, price_flight,reco['price'].iloc[0],reco['beds'].iloc[0],reco['People'].iloc[0],reco['number_of_reviews'].iloc[0], time, int(indicator))
    user_df = updated_user_df.copy()
    return pool_df, user_df, reco.iloc[0]

In [37]:
City = 'Barcelona' #inputed
prev = 50059918 # recursive
price_flight = 200 #inputed
category = 'Historical' #inputed
time = '2023-04-15 14:30:45' #inputed
from model import clf_Airbnb
pool_df, user_df, reco= clf_Airbnb(1,user_df,pool_df,df,City,price_flight,category,time,prev = 50059918)

Barcelona 50059918 50 1.5 1.5 500
Preciosa y espaciosa habitaciÃ³n con cama de matrimonio. Toallas (no de playa) y sabanas incluidas. Agua mineral en la habitaciÃ³n.<br />CalefacciÃ³n central. Ventilador. Parquet.<br />Amplia, exterior, luminosa y cÃ©ntrica. Con persiana para bloquear la luz completamente.<br />La  TELEVISIÃ“N Y NEVERITA son para tu uso exclusivo, armario ,  escritorio y wifi (FIBRA Ã“PTICA). <br />Zona a 10 minutos de la Plaza EspaÃ±a, autobÃºs en puerta.<br />Posibilidad de cuna, si se solicita .<br /><br /><b>The space</b><br />Espaciosa habitaciÃ³n con cama de matrimonio, escritorio, armario, wifi (fibra Ã³ptica). BaÃ±o completo compartido con la otra habitacion. tienes TELEVISIÃ“N en tu habitaciÃ³n, y una NEVERITA tipo hotel para tu uso exclusivo con agua mineral para ti.<br /><br /><b>Guest access</b><br />El cuarto de baÃ±o completo es compartido con otra habitaciÃ³n<br /><br /><b>Other things to note</b><br />Durante vuestra estancia os puedo ofrecer una experiencia inolvidable en un barco tradicional mallorqHABITACION CERCA CENTRO["Extra pillows and blankets", "Carbon monoxide alarm", "Room-darkening shades", "Clamp on table seat high chair", "TV", "Lock on bedroom door", "Dedicated workspace", "Paid parking off premises", "Hangers", "Heating", "Babysitter recommendations", "Long term stays allowed", "Shower gel", "First aid kit", "Private patio or balcony", "Bed linens", "Free street parking", "Body soap", "Host greets you", "Clothing storage: closet", "Hair dryer", "Shampoo", "Hot water", "Wifi", "Fire extinguisher", "Mountain view", "Essentials", "Elevator", "Smoke alarm"]
----------
40
----------
https://www.airbnb.com/rooms/2670047
Do you like this offer? 1 for yes, 0 for no

/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/userdata.py:117: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pool_df = pool_df.append(new_row, ignore_index=True)

In [40]:
reco

id                                                                  2670047
listing_url                            https://www.airbnb.com/rooms/2670047
description               Confortable apartamento de 80 m2 totalmente re...
host_is_superhost                                                         f
neighbourhood_cleansed                                         el Poble Sec
latitude                                                           41.37439
longitude                                                           2.16014
property_type                                            Entire rental unit
room_type                                                   Entire home/apt
accommodates                                                              6
bathrooms_text                                                      2 baths
beds                                                                    5.0
amenities                 ["Central heating", "Oven", "Private backyard ...
price                                                                 206.0
minimum_nights                                                            2
maximum_nights                                                           28
minimum_minimum_nights                                                  2.0
maximum_minimum_nights                                                  4.0
has_availability                                                          t
number_of_reviews                                                       412
instant_bookable                                                          f
City                                                              Barcelona
comments                  Excelente apartamento. The whole stay was amaz...
Text                      Confortable apartamento de 80 m2 totalmente re...
People                                                                  1.2
Min_Duration                                                            2.0
fear                                                                    0.0
anger                                                                   0.0
anticip                                                                 0.0
trust                                                              0.333333
surprise                                                           0.041667
positive                                                           0.416667
negative                                                                0.0
sadness                                                                 0.0
disgust                                                                 0.0
joy                                                                0.166667
Name: 3129, dtype: object

In [39]:
#updated_user_df = updated_user_df.drop('UserId',axis=1)
mask = user_df > 0
subset = user_df.loc[mask.any(axis=1), mask.any(axis=0)]

# print the selected rows and columns
subset

,PriceLvl_3,PriceLvl_10,PriceLvl_1_airbnb,PriceLvl_3_airbnb,PriceLvl_10_airbnb,Beds_1_airbnb,Beds_2_airbnb,Beds_4_airbnb,Beds_5_airbnb,People_2_airbnb,People_10_airbnb,Reviews_3_airbnb,Reviews_4_airbnb,Reviews_5_airbnb,Historical,UserId,Noon,Barcelona,Madrid
1,9,1,7,2,1,1,5,1,3,9,1,6,2,2,10,1,10,2,8
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,995,0,0,0
996,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,996,0,0,0
997,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,997,0,0,0
998,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,998,0,0,0
999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,999,0,0,0

In [45]:
from statistics import mean

mean(reviews_ranges[str(reviews_max_air)[5:-14]])

100

In [42]:

str(beds_max_air)[5:-14]

'Beds_1_airbnb'

In [45]:
#updated_user_df = updated_user_df.drop('UserId',axis=1)
mask = updated_user_df > 0
subset = updated_user_df.loc[mask.any(axis=1), mask.any(axis=0)]

# print the selected rows and columns
subset

     Historical  UserId  Noon  Madrid
1             1       1     1       1
2             0       2     0       0
3             0       3     0       0
4             0       4     0       0
5             0       5     0       0
..          ...     ...   ...     ...
995           0     995     0       0
996           0     996     0       0
997           0     997     0       0
998           0     998     0       0
999           0     999     0       0

[999 rows x 4 columns]

In [22]:
r.sort_values(['fear', 'anger', 'negative', 'sadness', 'disgust',]).sort_values([ 'number_of_reviews','trust', 'surprise','positive',  'joy'],ascending=False)

,id,listing_url,description,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,fear,anger,anticip,trust,surprise,positive,negative,sadness,disgust,joy
4504,18369830,https://www.airbnb.com/rooms/18369830,For us the establishment is very special becau...,t,Centro,36.72677,-4.41933,Entire rental unit,Entire home/apt,5,...,0.000000,0.000000,0.0,0.217391,0.043478,0.260870,0.000000,0.043478,0.000000,0.217391
4507,21466209,https://www.airbnb.com/rooms/21466209,With the accommodation what we have tried is t...,t,Bailen-Miraflores,36.72394,-4.43297,Entire rental unit,Entire home/apt,4,...,0.000000,0.000000,0.0,0.296296,0.037037,0.370370,0.000000,0.000000,0.000000,0.148148
4508,6225247,https://www.airbnb.com/rooms/6225247,Beautiful and big apartment at Plaza De Unciba...,t,Centro,36.72167,-4.42002,Entire rental unit,Entire home/apt,4,...,0.017094,0.008547,0.0,0.179487,0.068376,0.264957,0.076923,0.094017,0.008547,0.170940
4530,6077119,https://www.airbnb.com/rooms/6077119,"Our house is cosy, quiet, spacious, bright, wi...",t,Centro,36.71952,-4.42597,Entire rental unit,Entire home/apt,5,...,0.055556,0.055556,0.0,0.166667,0.055556,0.222222,0.055556,0.055556,0.055556,0.166667
4531,4066844,https://www.airbnb.com/rooms/4066844,. Apartments can accommodate up to 7 persons i...,f,Centro,36.72514,-4.42217,Entire rental unit,Entire home/apt,7,...,0.000000,0.026316,0.0,0.236842,0.052632,0.289474,0.052632,0.052632,0.000000,0.184211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5856,18614024,https://www.airbnb.com/rooms/18614024,This luxury villa is perfectly designed for fa...,f,Churriana,36.66465,-4.46054,Entire home,Entire home/apt,10,...,0.000000,0.000000,0.0,0.333333,0.000000,0.333333,0.000000,0.000000,0.000000,0.250000
5871,43482734,https://www.airbnb.com/rooms/43482734,A beautiful private Andalusian-style house wi...,t,Este,36.80206,-4.34453,Entire cottage,Entire home/apt,6,...,0.000000,0.000000,0.0,0.166667,0.000000,0.416667,0.000000,0.166667,0.000000,0.250000
5916,11183000,https://www.airbnb.com/rooms/11183000,The villa has 7 bedrooms each with private ...,t,Este,36.72798,-4.36470,Entire villa,Entire home/apt,16,...,0.000000,0.000000,0.0,0.500000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000
5930,10545967,https://www.airbnb.com/rooms/10545967,"House with private garden and shared pool, in ...",t,Este,36.76595,-4.30417,Entire rental unit,Entire home/apt,2,...,0.043478,0.000000,0.0,0.173913,0.000000,0.347826,0.043478,0.000000,0.000000,0.260870
5976,40840546,https://www.airbnb.com/rooms/40840546,Villa Garberi consists of 2 separate houses on...,t,Churriana,36.65306,-4.50855,Entire villa,Entire home/apt,9,...,0.000000,0.025974,0.0,0.194805,0.064935,0.363636,0.025974,0.012987,0.000000,0.181818