In [ ]:
"""
Sim:
- Text
- comments
"""
"""
Sort:
- City BOOLEN DONE

- price SORT 
- People SORT
- beds SORT
- number_of_reviews SORT
- 
"""
"""
Leave:
- 'index', 'id', 'listing_url','neighbourhood_cleansed','latitude', 'longitude','instant_bookable','accommodates','beds', maximum_nights, minimum_nights, 'name','description','amenities'
"""
"""

"""

In [1]:
import sys

# Add a path to sys.path
sys.path.append('../datasets')


from Airbnb_data import Airbnb_data
df = Airbnb_data()

In [3]:
df.sort_values('number_of_reviews')['number_of_reviews']

13999       4
13938       4
13939       4
13940       4
13941       4
         ...
10002     915
10001     928
10000    1011
4001     1044
4000     1612
Name: number_of_reviews, Length: 14000, dtype: int64

In [3]:
df.groupby('City').count()

,id,listing_url,description,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,price,minimum_nights,maximum_nights,has_availability,number_of_reviews,instant_bookable,comments,Text,People,Min_Duration
City,,,,,,,,,,,,,,,,,,,,,
Barcelona,11550,11550,11550,11550,11550,11550,11550,11550,11550,11550,...,11550,11550,11550,11550,11550,11550,11550,11550,11550,11550
Girona,13969,13969,13969,13969,13969,13969,13969,13969,13969,13969,...,13969,13969,13969,13969,13969,13969,13969,13969,13969,13969
Madrid,15465,15465,15465,15465,15465,15465,15465,15465,15465,15465,...,15465,15465,15465,15465,15465,15465,15465,15465,15465,15465
Malaga,6082,6082,6082,6082,6082,6082,6082,6082,6082,6082,...,6082,6082,6082,6082,6082,6082,6082,6082,6082,6082
Mallorca,12050,12050,12050,12050,12050,12050,12050,12050,12050,12050,...,12050,12050,12050,12050,12050,12050,12050,12050,12050,12050
Menorca,2699,2699,2699,2699,2699,2699,2699,2699,2699,2699,...,2699,2699,2699,2699,2699,2699,2699,2699,2699,2699
Sevilla,5961,5961,5961,5961,5961,5961,5961,5961,5961,5961,...,5961,5961,5961,5961,5961,5961,5961,5961,5961,5961

In [1]:
import sys

# Add a path to sys.path
sys.path.append('../datasets')

In [2]:
from Airbnb_reco import model_computations

In [3]:
titles_air,indices_air, cosine_sim_air, df = model_computations('comments')

50 PERCENT

In [4]:
import numpy as np
titles_air.to_csv('titles_comments_air.csv',index=False)
indices_air.to_csv('indices_comments_air.csv',index=False)
np.save('cosine_sim_comments_air.npy', cosine_sim_air)

NameError: name 'titles_air' is not defined

In [21]:
import sys

# Add a path to sys.path
sys.path.append('../datasets')

import pandas as pd
from Airbnb_data import Airbnb_data
df = Airbnb_data()
#listing_df_madrid = pd.read_csv("../datasets/data_files/listings_mad.csv")
#review_df_madrid = pd.read_csv("../datasets/data_files/reviews_mad.csv")

/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/Airbnb_data.py:216: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  result_df['price'] = result_df['price']/100

In [ ]:
df.to_csv('airbnb_clean.csv',index=False)

In [3]:
from Airbnb_reco import Airbnb_reco

In [35]:
df['People'].min()

0.1

In [18]:
import numpy as np
import sys
import pandas as pd
# Add a path to sys.path
sys.path.append('../datasets')

#titles,indices, cosine_sim, df = model_computations()
titles = pd.read_csv('../datasets/data_files/titles_air.csv')
df = pd.read_csv('../datasets/data_files/airbnb_clean.csv')
df2 = df.reset_index()
titles = pd.Series(df2['Text'])
indices = pd.Series(df2.index, index = df2['Text'])
cosine_sim = np.load('../datasets/data_files/cosine_sim_air.npy')

In [19]:
from Airbnb_reco import Airbnb_reco
r = Airbnb_reco('Malaga',50059918,200,10,2,100,titles,indices, cosine_sim, df)

Casa Bellavista is located in Caldes in an equipped urbanization, on the Costa Brava. Comfort, one floor; furnished, equipped kitchen with barbecue, living room with fireplace, 3 double bedrooms, and a suite with games room (billiards); 2 full baths, porch. 800 m2 garden with new 9x5 private pool with hydromassage bench, bunk bed and waterfall. Large barbecue, pergola. Ping pong table. Free wifi connection.<br />View of the natural park of animals (deer, peacock, emus).<br /><br /><b>The space</b><br />The villa includes 4 doubles bedrooms, 2 bathrooms: one is a fuller equipped bathroom (sink, bathtub, toilet..) and another with sink, shower and toilet. The villa includes a great and bright dining-room with a fireplace, and a fully equipped kitchen and also a fireplace. It has television. 55 "flat screen with Smart TV and Netflix. The house is fully furnished and equipped. They have free Wi-Fi throughout the space.<br />The 800m2 private garden ha a private swimming pool with a small wHOUSE WITH PRIVATE POOL IN CALDES COSTA BRAVA["Carbon monoxide alarm", "Changing table", "Free parking on premises", "Fireplace guards", "Pack \u2019n play/Travel crib", "Refrigerator", "Long term stays allowed", "Shampoo", "Outdoor shower", "Baking sheet", "Microwave", "Body soap", "Pool table", "First aid kit", "Garden view", "Private entrance", "Free street parking", "Luggage dropoff allowed", "Pets allowed", "Hangers", "Children\u2019s books and toys", "Room-darkening shades", "Dishes and silverware", "Bed linens", "Babysitter recommendations", "Shower gel", "Heating", "Cooking basics", "Smoke alarm", "Toaster", "Private backyard \u2013 Fully fenced", "Outdoor furniture", "Private patio or balcony", "Indoor fireplace: wood-burning", "Ping pong table", "Bathtub", "Building staff", "High chair", "Clothing storage", "Cleaning products", "AC - split type ductless system", "Pool view", "Hot water", "Free washer \u2013 In unit", "Oven", "Crib", "Private outdoor pool - available all year, open 24 hours, infinity", "Mini fridge", "Hair dryer", "Kitchen", "Iron", "Wine glasses", "Ethernet connection", "Dishwasher", "Extra pillows and blankets", "Barbecue utensils", "Dining table", "BBQ grill", "Single level home", "Outdoor dining area", "55\" HDTV with Chromecast, Netflix", "Hot water kettle", "Coffee maker", "Self check-in", "Children\u2019s dinnerware", "Smoking allowed", "Essentials", "Park view", "Wifi"]
----------
70
----------

In [20]:
def Rent_Reco(location,previous,best_price,best_beds,best_People,best_reviews):
        
    recos = Airbnb_reco(location,previous,best_price,best_beds,best_People,best_reviews,titles,indices, cosine_sim, df)
    return recos.head(50)

In [1]:
import pandas as pd

df = pd.read_csv('../datasets/data_files/airbnb_clean.csv')

import sys
sys.path.append('../datasets')
from userdata import users
import numpy as np
from data_structure import data_strcture
_, user_df, pool_df = data_strcture()

/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/Flights.py:12: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df['bags_price'] = grouped_bag['bags_price'].apply(lambda x: x.fillna(x.dropna().iloc[0]) if x.isnull().values.any() else x)
/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/Flights.py:13: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df['availability'] = grouped_avl['availability'].apply(lambda x: x.fillna(x.dropna().iloc[0]) if x.isnull().values.any() else x)
/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/Flights.py:12: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df['bags_price'] = grouped_bag['bags_price'].apply(lambda x: x.fillna(x.dropna().iloc[0]) if x.isnull().values.any() else x)
/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/Flights.py:13: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df['availability'] = grouped_avl['availability'].apply(lambda x: x.fillna(x.dropna().iloc[0]) if x.isnull().values.any() else x)
/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/data_structure.py:86: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pool_df[x] = y

In [4]:
pool_df, updated_user_df = users(1 ,df, user_df, pool_df, 'Madrid', 'Historical', 900,900,5,10,800, '2023-04-15 14:30:45', 0)

/home/yousif/Desktop/All/IE_Third_Year_2/RS/Project_All/Tourism-Recommendation-System/lib/models/../datasets/userdata.py:117: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pool_df = pool_df.append(new_row, ignore_index=True)

In [9]:
#updated_user_df = updated_user_df.drop('UserId',axis=1)
mask = updated_user_df > 0
subset = updated_user_df.loc[mask.any(axis=1), mask.any(axis=0)]

# print the selected rows and columns
subset

     UserId
1         1
2         2
3         3
4         4
5         5
..      ...
995     995
996     996
997     997
998     998
999     999

[999 rows x 1 columns]

In [17]:
price_max_air = user_df[user_df['UserId'] == 1].filter(regex='PriceLvl.*airbnb').idxmax(axis=1)
beds_max_air = user_df[user_df['UserId']==1].filter(like='Beds_').idxmax(axis=1)
people_max_air = user_df[user_df['UserId']==1].filter(like='People_').idxmax(axis=1)
reviews_max_air = user_df[user_df['UserId']==1].filter(like='Reviews_').idxmax(axis=1)

In [52]:
from Ranges import Ranges
from statistics import mean
#pool_df, updated_user_df = users(1 ,df, user_df, pool_df, 'Madrid', 'Historical', 900,900,5,10,800, '2023-04-15 14:30:45', 0)

price_ranges, time_cols_dict, cities_dict, price_ranges_air, beds_ranges, people_ranges, reviews_ranges = Ranges()
City = 'Madrid' #inputed
prev = 50059918 # recursive
price_flight = 200 #inputed
category = 'Historical' #inputed
time = '2023-04-15 14:30:45' #inputed
best_price_air = mean(price_ranges_air[str(price_max_air)[5:-14]])
best_beds_air = mean(beds_ranges[str(beds_max_air)[5:-14]])
best_people_air = mean(people_ranges[str(people_max_air)[5:-14]])
best_reviews_air = mean(reviews_ranges[str(reviews_max_air)[5:-14]])

reco = Rent_Reco(City,prev, best_price_air,best_beds_air,best_people_air, best_reviews_air)
reco = reco.sort_values(['fear', 'anger', 'negative', 'sadness', 'disgust',]).sort_values([ 'number_of_reviews','trust', 'surprise','positive',  'joy'],ascending=False)
reco = reco.head(10)
print(reco['listing_url'].iloc[0])
print("Do you like this offer? 1 for yes, 0 for no")
indicator = input()
pool_df, updated_user_df = users(1 ,df, user_df, pool_df, reco['City'].iloc[0], category, price_flight,reco['price'].iloc[0], time, int(indicator))

Rogamos lea detenidamente todo el contenido del anuncio y evitar mal entendidos en cuanto al espacio.<br /><br />El piso donde nos encontramos es muy acogedor. Se trata de un primer piso sin ascensor, ubicado a 2 minutos del Paseo marÃ­timo.<br />Perfecto si viaja solo y desea conocer la isla o por visitas de trabajo.<br /><br />Nos encontramos muy cerca de La lonja, la Catedral, el casco antiguo. El centro de palma queda a unos 20 o 30 minutos caminando. <br />Buenas conexiones con el transporte pÃºblico en general.<br /><br /><b>The space</b><br />El piso en general tiene muy buena iluminaciÃ³n natural.<br /><br />La habitaciÃ³n estÃ¡ compuesta por una cama de 90, armarios y un buen escritorio, con buena instalaciÃ³n lumÃ­nica y CON VENTANA AL INTERIOR DEL HOGAR (no al exterior). Los productos de aseo estÃ¡n incluidos (ChampÃº, gel, papel higiÃ©nico, secador de pelo).<br />TambiÃ©n cuenta con televisiÃ³n.<br /><br />La habitaciÃ³n cuenta con aire acondicionado frio/calor. (se ruega al huÃ©sped dejHabitaciÃ³n interior en Palma con Wifi.["Extra pillows and blankets", "Room-darkening shades", "Hot water kettle", "TV", "Laundromat nearby", "Lock on bedroom door", "Dedicated workspace", "Hangers", "Refrigerator", "Heating", "Shower gel", "Bidet", "Bed linens", "Coffee maker", "Clothing storage: dresser and closet", "Body soap", "Coffee", "Host greets you", "Hair dryer", "Shampoo", "Hot water", "Luggage dropoff allowed", "Wifi", "Essentials", "Iron", "Dining table", "Waterfront", "Air conditioning"]
----------
166
----------
1517    https://www.airbnb.com/rooms/16675905
Name: listing_url, dtype: object

In [50]:
reco.head()

,id,listing_url,description,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,fear,anger,anticip,trust,surprise,positive,negative,sadness,disgust,joy
1517,16675905,https://www.airbnb.com/rooms/16675905,"Bonito piso en planta baja de 2 habitaciones, ...",f,Embajadores,40.40621,-3.70227,Entire rental unit,Entire home/apt,4,...,0.000000,0.000000,0.0,0.230769,0.076923,0.269231,0.076923,0.000000,0.000000,0.153846
1530,28237489,https://www.airbnb.com/rooms/28237489,HabitaciÃ³n doble con entrada independiente (di...,t,Casco HistÃ³rico de Barajas,40.47369,-3.58161,Private room in home,Private room,2,...,0.000000,0.000000,0.0,0.166667,0.000000,0.333333,0.000000,0.000000,0.000000,0.333333
1535,6287069,https://www.airbnb.com/rooms/6287069,"HabitaciÃ³n Exterior con balcÃ³n a la calle , ca...",f,Universidad,40.42335,-3.70759,Private room in home,Private room,2,...,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
1548,6720443,https://www.airbnb.com/rooms/6720443,"Muy bien situado , caminando 15/20 minutos de ...",f,Puerta del Angel,40.41400,-3.72436,Entire rental unit,Entire home/apt,11,...,0.107143,0.107143,0.0,0.142857,0.035714,0.107143,0.178571,0.107143,0.071429,0.071429
1550,18501380,https://www.airbnb.com/rooms/18501380,HabitaciÃ³n exterior con aire acondicionado y c...,t,San Diego,40.39180,-3.66922,Private room in rental unit,Private room,2,...,0.000000,0.000000,0.0,0.363636,0.000000,0.363636,0.000000,0.000000,0.000000,0.181818

In [45]:
from statistics import mean

mean(reviews_ranges[str(reviews_max_air)[5:-14]])

100

In [42]:

str(beds_max_air)[5:-14]

'Beds_1_airbnb'

In [45]:
#updated_user_df = updated_user_df.drop('UserId',axis=1)
mask = updated_user_df > 0
subset = updated_user_df.loc[mask.any(axis=1), mask.any(axis=0)]

# print the selected rows and columns
subset

     Historical  UserId  Noon  Madrid
1             1       1     1       1
2             0       2     0       0
3             0       3     0       0
4             0       4     0       0
5             0       5     0       0
..          ...     ...   ...     ...
995           0     995     0       0
996           0     996     0       0
997           0     997     0       0
998           0     998     0       0
999           0     999     0       0

[999 rows x 4 columns]

In [22]:
r.sort_values(['fear', 'anger', 'negative', 'sadness', 'disgust',]).sort_values([ 'number_of_reviews','trust', 'surprise','positive',  'joy'],ascending=False)

,id,listing_url,description,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,fear,anger,anticip,trust,surprise,positive,negative,sadness,disgust,joy
4504,18369830,https://www.airbnb.com/rooms/18369830,For us the establishment is very special becau...,t,Centro,36.72677,-4.41933,Entire rental unit,Entire home/apt,5,...,0.000000,0.000000,0.0,0.217391,0.043478,0.260870,0.000000,0.043478,0.000000,0.217391
4507,21466209,https://www.airbnb.com/rooms/21466209,With the accommodation what we have tried is t...,t,Bailen-Miraflores,36.72394,-4.43297,Entire rental unit,Entire home/apt,4,...,0.000000,0.000000,0.0,0.296296,0.037037,0.370370,0.000000,0.000000,0.000000,0.148148
4508,6225247,https://www.airbnb.com/rooms/6225247,Beautiful and big apartment at Plaza De Unciba...,t,Centro,36.72167,-4.42002,Entire rental unit,Entire home/apt,4,...,0.017094,0.008547,0.0,0.179487,0.068376,0.264957,0.076923,0.094017,0.008547,0.170940
4530,6077119,https://www.airbnb.com/rooms/6077119,"Our house is cosy, quiet, spacious, bright, wi...",t,Centro,36.71952,-4.42597,Entire rental unit,Entire home/apt,5,...,0.055556,0.055556,0.0,0.166667,0.055556,0.222222,0.055556,0.055556,0.055556,0.166667
4531,4066844,https://www.airbnb.com/rooms/4066844,. Apartments can accommodate up to 7 persons i...,f,Centro,36.72514,-4.42217,Entire rental unit,Entire home/apt,7,...,0.000000,0.026316,0.0,0.236842,0.052632,0.289474,0.052632,0.052632,0.000000,0.184211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5856,18614024,https://www.airbnb.com/rooms/18614024,This luxury villa is perfectly designed for fa...,f,Churriana,36.66465,-4.46054,Entire home,Entire home/apt,10,...,0.000000,0.000000,0.0,0.333333,0.000000,0.333333,0.000000,0.000000,0.000000,0.250000
5871,43482734,https://www.airbnb.com/rooms/43482734,A beautiful private Andalusian-style house wi...,t,Este,36.80206,-4.34453,Entire cottage,Entire home/apt,6,...,0.000000,0.000000,0.0,0.166667,0.000000,0.416667,0.000000,0.166667,0.000000,0.250000
5916,11183000,https://www.airbnb.com/rooms/11183000,The villa has 7 bedrooms each with private ...,t,Este,36.72798,-4.36470,Entire villa,Entire home/apt,16,...,0.000000,0.000000,0.0,0.500000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000
5930,10545967,https://www.airbnb.com/rooms/10545967,"House with private garden and shared pool, in ...",t,Este,36.76595,-4.30417,Entire rental unit,Entire home/apt,2,...,0.043478,0.000000,0.0,0.173913,0.000000,0.347826,0.043478,0.000000,0.000000,0.260870
5976,40840546,https://www.airbnb.com/rooms/40840546,Villa Garberi consists of 2 separate houses on...,t,Churriana,36.65306,-4.50855,Entire villa,Entire home/apt,9,...,0.000000,0.025974,0.0,0.194805,0.064935,0.363636,0.025974,0.012987,0.000000,0.181818